AllCops:
  NewCops: enable

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/IndentHash:
  Enabled: true
  Width: 2

Layout/IndentArray:
  Enabled: true
  Width: 2

Layout/IndentAssignment:
  Enabled: true
  Width: 2

Layout/IndentHeredoc:
  Enabled: true
  Width: 2

Layout/IndentFirstArgument:
  Enabled: true
  Width: 2

Layout/IndentFirstArrayElement:
  Enabled: true
  Width: 2

Layout/IndentFirstHashElement:
  Enabled: true
  Width: 2

Layout/IndentFirstParameter:
  Enabled: true
  Width: 2
